part of 'quizzes_resource.dart';

extension Category1Quiz on QuizModel {
  ///問題ジャンル
  List<Quiz> get category1QuizList => [
        Quiz(
          id: 1,
          categoryId: 1,
          category: I18n().setCategory(1),
          title: "経営・組織論①",
          quizItemList: category1_1,
        ),
        Quiz(
          id: 2,
          categoryId: 1,
          category: I18n().setCategory(1),
          title: "経営・組織論②",
          quizItemList: category1_2,
        ),
        Quiz(
          id: 3,
          categoryId: 1,
          category: I18n().setCategory(1),
          title: "経営・組織論③",
          quizItemList: category1_3,
        ),
        Quiz(
          id: 4,
          categoryId: 1,
          category: I18n().setCategory(1),
          title: "経営・組織論④",
          quizItemList: category1_4,
        ),
        Quiz(
          id: 5,
          categoryId: 1,
          category: I18n().setCategory(1),
          title: "経営・組織論⑤",
          quizItemList: category1_5,
        ),
        Quiz(
          id: 6,
          categoryId: 1,
          category: I18n().setCategory(1),
          title: "分析・データ活用①",
          quizItemList: category1_6,
        ),
        Quiz(
          id: 7,
          categoryId: 1,
          category: I18n().setCategory(1),
          title: "分析・データ活用②",
          quizItemList: category1_7,
        ),
        Quiz(
          id: 8,
          categoryId: 1,
          category: I18n().setCategory(1),
          title: "分析・データ活用③",
          quizItemList: category1_8,
        ),
        Quiz(
          id: 9,
          categoryId: 1,
          category: I18n().setCategory(1),
          title: "分析・データ活用④",
          quizItemList: category1_9,
        ),
        Quiz(
          id: 10,
          categoryId: 1,
          category: I18n().setCategory(1),
          title: "分析・データ活用⑤",
          quizItemList: category1_10,
        ),
        Quiz(
          id: 11,
          categoryId: 1,
          category: I18n().setCategory(1),
          title: "会計・財務①",
          quizItemList: category1_11,
        ),
        Quiz(
          id: 12,
          categoryId: 1,
          category: I18n().setCategory(1),
          title: "会計・財務②",
          quizItemList: category1_12,
        ),
        Quiz(
          id: 13,
          categoryId: 1,
          category: I18n().setCategory(1),
          title: "知的財産権①",
          quizItemList: category1_13,
        ),
        Quiz(
          id: 14,
          categoryId: 1,
          category: I18n().setCategory(1),
          title: "知的財産権②",
          quizItemList: category1_14,
        ),
        Quiz(
          id: 15,
          categoryId: 1,
          category: I18n().setCategory(1),
          title: "セキュリティ関連法規①",
          quizItemList: category1_15,
        ),
        Quiz(
          id: 16,
          categoryId: 1,
          category: I18n().setCategory(1),
          title: "セキュリティ関連法規②",
          quizItemList: category1_16,
        ),
        Quiz(
          id: 17,
          categoryId: 1,
          category: I18n().setCategory(1),
          title: "労働関連・取引関連法規",
          quizItemList: category1_17,
        ),
        Quiz(
          id: 18,
          categoryId: 1,
          category: I18n().setCategory(1),
          title: "ガイドライン",
          quizItemList: category1_18,
        ),
        Quiz(
          id: 19,
          categoryId: 1,
          category: I18n().setCategory(1),
          title: "標準化関連①",
          quizItemList: category1_19,
        ),
        Quiz(
          id: 20,
          categoryId: 1,
          category: I18n().setCategory(1),
          title: "標準化関連②",
          quizItemList: category1_20,
        ),
        Quiz(
          id: 21,
          categoryId: 1,
          category: I18n().setCategory(1),
          title: "経営戦略手法①",
          quizItemList: category1_21,
        ),
        Quiz(
          id: 22,
          categoryId: 1,
          category: I18n().setCategory(1),
          title: "経営戦略手法②",
          quizItemList: category1_22,
        ),
        Quiz(
          id: 23,
          categoryId: 1,
          category: I18n().setCategory(1),
          title: "経営戦略手法③",
          quizItemList: category1_23,
        ),
        Quiz(
          id: 24,
          categoryId: 1,
          category: I18n().setCategory(1),
          title: "マーケティング①",
          quizItemList: category1_24,
        ),
        Quiz(
          id: 25,
          categoryId: 1,
          category: I18n().setCategory(1),
          title: "マーケティング②",
          quizItemList: category1_25,
        ),
        Quiz(
          id: 26,
          categoryId: 1,
          category: I18n().setCategory(1),
          title: "マーケティング③",
          quizItemList: category1_26,
        ),
        Quiz(
          id: 27,
          categoryId: 1,
          category: I18n().setCategory(1),
          title: "マーケティング④",
          quizItemList: category1_27,
        ),
        Quiz(
          id: 28,
          categoryId: 1,
          category: I18n().setCategory(1),
          title: "経営管理システム",
          quizItemList: category1_28,
        ),
        Quiz(
          id: 29,
          categoryId: 1,
          category: I18n().setCategory(1),
          title: "技術戦略マネジメント①",
          quizItemList: category1_29,
        ),
        Quiz(
          id: 30,
          categoryId: 1,
          category: I18n().setCategory(1),
          title: "技術戦略マネジメント②",
          quizItemList: category1_30,
        ),
        Quiz(
          id: 31,
          categoryId: 1,
          category: I18n().setCategory(1),
          title: "エンジニアリングシステム",
          quizItemList: category1_31,
        ),
        Quiz(
          id: 32,
          categoryId: 1,
          category: I18n().setCategory(1),
          title: "e-ビジネス①",
          quizItemList: category1_32,
        ),
        Quiz(
          id: 33,
          categoryId: 1,
          category: I18n().setCategory(1),
          title: "e-ビジネス②",
          quizItemList: category1_33,
        ),
        Quiz(
          id: 34,
          categoryId: 1,
          category: I18n().setCategory(1),
          title: "IoTシステム・組込みシステム①",
          quizItemList: category1_34,
        ),
        Quiz(
          id: 35,
          categoryId: 1,
          category: I18n().setCategory(1),
          title: "IoTシステム・組込みシステム②",
          quizItemList: category1_35,
        ),
        Quiz(
          id: 36,
          categoryId: 1,
          category: I18n().setCategory(1),
          title: "業務プロセス①",
          quizItemList: category1_36,
        ),
        Quiz(
          id: 37,
          categoryId: 1,
          category: I18n().setCategory(1),
          title: "業務プロセス②",
          quizItemList: category1_37,
        ),
        Quiz(
          id: 38,
          categoryId: 1,
          category: I18n().setCategory(1),
          title: "ソリューションビジネス",
          quizItemList: category1_38,
        ),
        Quiz(
          id: 39,
          categoryId: 1,
          category: I18n().setCategory(1),
          title: "システム活用促進・評価",
          quizItemList: category1_39,
        ),
        Quiz(
          id: 40,
          categoryId: 1,
          category: I18n().setCategory(1),
          title: "システム企画",
          quizItemList: category1_40,
        ),
      ];
}
