name: kentei_quiz
description: A new Flutter application.
publish_to: none

# アプリバージョン
# [メジャーバージョン].[マイナーバージョン].[パッチバージョン]+[ビルド番号]
#
# - ストアでバージョン x.y.z+a が審査承認済みなとき、次にアップロードするバージョンは x.y.(z+1)+(a+1)
# - ストアにバージョン x.y.z+a をアップロード済みのとき、次にアップロードするバージョンは x.y.z+(a+1)
version: 1.1.2+17

environment:
  sdk: ">=2.16.2 <4.0.0"
  # 次の一行を記述するとビルドに使用する flutter sdk version を指定できる
  # Note: ビルドに使用する flutter sdk version は flutter version コマンドで選択できる
  # Warn: main.ymlも合わせて変えること！！！

dependencies:
  flutter:
    sdk: flutter
  #  他言語対応したい
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0
  localization: ^2.1.0

  cupertino_icons: ^1.0.2

  # よりよいproviderを使いたい
  hooks_riverpod: ^2.3.7
  provider: ^6.0.2

  # StateNotifierを使って状態管理したい
  state_notifier: ^0.7.2+1
  flutter_state_notifier: ^0.7.1

  # データクラスのEqualsとかcopyWithとかを自動生成したい
  freezed_annotation: ^2.2.0

  # Textの文字サイズを自動で調整したい
  auto_size_text: ^3.0.0

  # アプリのローカルストレージに値を保存したい
  shared_preferences: ^2.1.0

  #  Listをグループ化したい
  grouped_list: ^5.1.2

  # Row or Column の中に楽にスペースを挿入したい
  gap: ^3.0.0

  #firebase関連を導入したい
  firebase_core: ^2.9.0
  firebase_auth: ^4.4.0
  cloud_firestore: ^4.5.0
  cloud_functions: ^4.1.0
  firebase_messaging: ^14.4.0
  firebase_storage: ^11.1.0
  firebase_crashlytics: ^3.3.3
  firebase_analytics: ^10.2.0
  firebase_dynamic_links: ^5.1.0
  firebase_in_app_messaging: ^0.7.1
  firebase_performance: ^0.9.1
  firebase_database: ^10.1.0
  firebase_remote_config: ^4.0.0

  #キーワードと一致する文字列をハイライトしたい。
  substring_highlight: ^1.0.33

  #freezed用
  analyzer: ^5.11.1

  #設定画面を反映させたい
  settings_ui: ^2.0.2

  #ほかのSNSからログインしたい
  google_sign_in: ^6.1.0

  #カルセールスライダーを使いたい
  carousel_slider: ^4.1.1

  #インジケーターをアニメーションしたい
  smooth_page_indicator: ^1.0.0+2

  #プロフィール画像を選択したい
  image_picker: ^1.0.1

  #生年月日をドラムロールしたい
  flutter_datetime_picker_plus: ^2.0.1

  #freezed用
  json_annotation: ^4.8.1

  #広告を入れたい
  google_mobile_ads: ^4.0.0

  #スプラッシュ画面を簡単に作成したい
  flutter_native_splash: ^2.2.19

  #さまざまなアイコンを追加したい
  font_awesome_flutter: ^10.5.0

  #グラフを作成したい
  fl_chart: ^0.62.0

  #アプリのバージョンを確認したい

  #ローディング画面をおしゃれにしたい
  flutter_spinkit: ^5.2.0

  #CircularProgressIndicator をカスタムしたい
  syncfusion_flutter_gauges: ^21.2.4

  #レビュー評価してもらいたい
  in_app_review: ^2.0.6

  flutter_hooks: ^0.18.6
  flutter_gen: ^5.3.1
  bordered_text: ^2.0.0

  #おしゃれなアイコンを使いたい。
  line_icons: ^2.0.3

  #urlを遷移したい。
  url_launcher: ^6.1.14

  #スケルトンローディングを表示したい。
  shimmer: ^3.0.0

  #Tider風スイワイプをしたい
  appinio_swiper: ^2.0.3

  #通知を実装したい
  flutter_local_notifications: ^17.1.0
  permission_handler: ^11.0.1
  flutter_native_timezone_updated_gradle: ^2.0.3

  #アイコン管理を簡単にしたい
  flutter_launcher_icons: ^0.13.1

  #webviewを使用したい
  webview_flutter: ^4.4.4

  #アプリ外に共有したい
  #  share_plus: ^7.2.1

  #SVGの画像を使用したい
  flutter_svg: ^2.0.9

  #アプリのバージョンを確認したい
  package_info_plus: ^4.2.0

  #デバイスの情報を確認したい
  device_info_plus: ^9.1.2

  #アプリ内課金を実装したい
  purchases_flutter: ^6.25.0

  #トラッキングポリシーモーダルを表示したい
  app_tracking_transparency: ^2.0.5

  #簡単にアニメーションをつけたい
  easy_animate: ^0.0.3

  #チュートリアルでコーチマークをつけたい
  tutorial_coach_mark: ^1.2.11

  #アニメーション画像を導入したい
  lottie: ^2.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

  # freezed用
  json_serializable: ^6.6.2
  freezed: ^2.3.2
  build_runner: ^2.4.6

  #様々なデバイス上でのレイアウトを確認したい
  device_preview: ^1.0.0

  device_preview_screenshot: ^1.0.0

flutter:
  uses-material-design: true
  #  自動姿勢フラグの有効
  generate: true

  #画像
  assets:
    - assets/animation/
    - assets/icon/
    - assets/image/
    - assets/image/premium/
    - assets/launcher/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: 'assets/launcher/app_icon_ios.png'
  image_path_android: 'assets/launcher/app_icon_android.png'
  image_path_ios: 'assets/launcher/app_icon_ios.png'
  adaptive_icon_background: '#ffffff'
  adaptive_icon_foreground: 'assets/launcher/app_icon_android.png'

