name: kentei_quiz
description: A new Flutter application.
publish_to: none

# アプリバージョン
# [メジャーバージョン].[マイナーバージョン].[パッチバージョン]+[ビルド番号]
#
# - ストアでバージョン x.y.z+a が審査承認済みなとき、次にアップロードするバージョンは x.y.(z+1)+(a+1)
# - ストアにバージョン x.y.z+a をアップロード済みのとき、次にアップロードするバージョンは x.y.z+(a+1)
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"
  # 次の一行を記述するとビルドに使用する flutter sdk version を指定できる
  # Note: ビルドに使用する flutter sdk version は flutter version コマンドで選択できる
  # Warn: main.ymlも合わせて変えること！！！

dependencies:
  flutter:
    sdk: flutter
  #  他言語対応したい
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  localization: ^2.1.0

  cupertino_icons: ^1.0.2

  # よりよいproviderを使いたい
  hooks_riverpod: ^2.3.4
  provider: ^6.0.2

  # StateNotifierを使って状態管理したい
  state_notifier: ^0.7.2+1
  flutter_state_notifier: ^0.7.1

  # データクラスのEqualsとかcopyWithとかを自動生成したい
  freezed_annotation: ^2.2.0

  # Textの文字サイズを自動で調整したい
  auto_size_text: ^3.0.0

  # アプリのローカルストレージに値を保存したい
  shared_preferences: ^2.1.0

  #様々なデバイス上でのレイアウトを確認したい
  device_preview: ^1.0.0
  device_preview_screenshot: ^1.0.0

  #  Listをグループ化したい
  grouped_list: ^5.1.2

  # Row or Column の中に楽にスペースを挿入したい
  gap: ^2.0.0

  #firebase関連を導入したい
  firebase_core: ^2.9.0
  firebase_auth: ^4.4.0
  cloud_firestore: ^4.5.0
  cloud_functions: ^4.1.0
  firebase_messaging: ^14.4.0
  firebase_storage: ^11.1.0
  firebase_crashlytics: ^3.1.0
  firebase_analytics: ^10.2.0
  firebase_dynamic_links: ^5.1.0
  firebase_in_app_messaging: ^0.7.1
  firebase_performance: ^0.9.1
  firebase_database: ^10.1.0
  firebase_remote_config: ^4.0.0

  #キーワードと一致する文字列をハイライトしたい。
  substring_highlight: ^1.0.33

  #freezed用
  analyzer: ^5.2.0

  #設定画面を反映させたい
  settings_ui: ^2.0.2

  #ほかのSNSからログインしたい
  google_sign_in: ^6.1.0
  flutter_signin_button: ^2.0.0

  #カルセールスライダーを使いたい
  carousel_slider: ^4.1.1

  #インジケーターをアニメーションしたい
  smooth_page_indicator: ^1.0.0+2

  #プロフィール画像を選択したい
  image_picker: ^0.8.6+3

  #生年月日をドラムロールしたい
  flutter_datetime_picker: ^1.5.1

  #freezed用
  json_annotation: ^4.8.0

  #広告を入れたい
  google_mobile_ads: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

  # freezed用
  json_serializable: ^6.2.0
  build_runner: ^2.2.0
  freezed: ^2.3.2

flutter:
  uses-material-design: true
  #  自動姿勢フラグの有効
  generate: true

  #画像
  assets:
    - assets/icon/
    - assets/image/

