name: kentei_quiz
description: A new Flutter application.
publish_to: none

# アプリバージョン
# [メジャーバージョン].[マイナーバージョン].[パッチバージョン]+[ビルド番号]
#
# - ストアでバージョン x.y.z+a が審査承認済みなとき、次にアップロードするバージョンは x.y.(z+1)+(a+1)
# - ストアにバージョン x.y.z+a をアップロード済みのとき、次にアップロードするバージョンは x.y.z+(a+1)
version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"
  # 次の一行を記述するとビルドに使用する flutter sdk version を指定できる
  # Note: ビルドに使用する flutter sdk version は flutter version コマンドで選択できる
  # Warn: main.ymlも合わせて変えること！！！

dependencies:
  flutter:
    sdk: flutter
  #  他言語対応したい
  flutter_localizations:
    sdk: flutter
  intl: ^0.17.0
  localization: ^2.1.0

  cupertino_icons: ^1.0.2

  # よりよいproviderを使いたい
  hooks_riverpod: ^1.0.3
  provider: ^6.0.2

  # StateNotifierを使って状態管理したい
  state_notifier: ^0.7.2+1
  flutter_state_notifier: ^0.7.1

  # データクラスのEqualsとかcopyWithとかを自動生成したい
  freezed_annotation: ^1.1.0

  # Textの文字サイズを自動で調整したい
  auto_size_text: ^3.0.0

  # アプリのローカルストレージに値を保存したい
  shared_preferences: ^2.0.13

  #様々なデバイス上でのレイアウトを確認したい
  device_preview: ^1.0.0
  device_preview_screenshot: ^1.0.0

  #  Listをグループ化したい
  grouped_list: ^4.2.0

  # Row or Column の中に楽にスペースを挿入したい
  gap: ^2.0.0

  #firebase関連を導入したい
  firebase_core: ^1.16.0
  firebase_auth: ^3.3.17
  cloud_firestore: ^3.1.14
  cloud_functions: ^3.2.14
  firebase_messaging: ^11.3.0
  firebase_storage: ^10.2.15
  firebase_crashlytics: ^2.7.2
  firebase_analytics: ^9.1.7
  firebase_dynamic_links: ^4.2.2
  firebase_in_app_messaging: ^0.6.0+13
  firebase_performance: ^0.8.0+11
  firebase_database: ^9.0.13
  firebase_remote_config: ^2.0.6

  #キーワードと一致する文字列をハイライトしたい。
  substring_highlight: ^1.0.33
  analyzer: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

  # freezed用
  json_serializable: ^6.2.0
  build_runner: ^2.2.0
  freezed: ^1.1.1

flutter:
  uses-material-design: true
  #  自動姿勢フラグの有効
  generate: true
