part of 'quiz_model.dart';

extension QuizModelEx on QuizModel {
  ///問題ジャンル
  List<Quiz> get initQuizList => [
        Quiz(
          id: 1,
          category: I18n().group1,
          title: "問題A-1",
          isCompleted: false,
          quizItemList: quiz1,
          correctNum: 0,
          timeStamp: null,
          duration: Duration.zero,
          studyType: StudyType.learn,
        ),
        Quiz(
          id: 2,
          category: I18n().group1,
          title: "問題A-2",
          isCompleted: false,
          quizItemList: quiz2,
          correctNum: 0,
          timeStamp: null,
          duration: Duration.zero,
          studyType: StudyType.learn,
        ),
        Quiz(
          id: 3,
          category: I18n().group2,
          title: "問題B-1",
          isCompleted: false,
          quizItemList: quiz3,
          correctNum: 0,
          timeStamp: null,
          duration: Duration.zero,
          studyType: StudyType.learn,
        ),
        Quiz(
          id: 4,
          category: I18n().group2,
          title: "問題B-2",
          isCompleted: false,
          quizItemList: quiz1,
          correctNum: 0,
          timeStamp: null,
          duration: Duration.zero,
          studyType: StudyType.learn,
        ),
        Quiz(
          id: 5,
          category: I18n().group3,
          title: "問題C-1",
          isCompleted: false,
          quizItemList: quiz2,
          correctNum: 0,
          timeStamp: null,
          duration: Duration.zero,
          studyType: StudyType.learn,
        ),
        Quiz(
          id: 6,
          category: I18n().group3,
          title: "問題C-2",
          isCompleted: false,
          quizItemList: quiz3,
          correctNum: 0,
          timeStamp: null,
          duration: Duration.zero,
          studyType: StudyType.learn,
        ),
        Quiz(
          id: 7,
          category: I18n().group1,
          title: "問題A-3",
          isCompleted: false,
          quizItemList: quiz1,
          correctNum: 0,
          timeStamp: null,
          duration: Duration.zero,
          studyType: StudyType.learn,
        ),
        Quiz(
          id: 8,
          category: I18n().group2,
          title: "問題B-3",
          isCompleted: false,
          quizItemList: quiz2,
          correctNum: 0,
          timeStamp: null,
          duration: Duration.zero,
          studyType: StudyType.learn,
        ),
        Quiz(
          id: 9,
          category: I18n().group3,
          title: "問題C-3",
          isCompleted: false,
          quizItemList: quiz3,
          correctNum: 0,
          timeStamp: null,
          duration: Duration.zero,
          studyType: StudyType.learn,
        ),
        Quiz(
          id: 10,
          category: I18n().group4,
          title: "問題D-1",
          isCompleted: false,
          quizItemList: quiz1,
          correctNum: 0,
          timeStamp: null,
          duration: Duration.zero,
          studyType: StudyType.learn,
        ),
        Quiz(
          id: 11,
          category: I18n().group4,
          title: "問題D-2",
          isCompleted: false,
          quizItemList: quiz2,
          correctNum: 0,
          timeStamp: null,
          duration: Duration.zero,
          studyType: StudyType.learn,
        ),
      ];

  ///今日のクイズ
  Quiz get initDailyQuiz => const Quiz(
        id: 1,
        category: "daily",
        title: "今日のクイズ",
        isCompleted: false,
        quizItemList: [],
        correctNum: 0,
        timeStamp: null,
        duration: Duration.zero,
        studyType: StudyType.learn,
      );

  ///苦手克服
  Quiz get initWeakQuiz => const Quiz(
        id: 2,
        category: "weak",
        title: "苦手克服",
        isCompleted: false,
        quizItemList: [],
        correctNum: 0,
        timeStamp: null,
        duration: Duration.zero,
        studyType: StudyType.learn,
      );

  ///力だめし
  Quiz get initTestQuiz => const Quiz(
        id: 3,
        category: "test",
        title: "力だめし",
        isCompleted: false,
        quizItemList: [],
        correctNum: 0,
        timeStamp: null,
        duration: Duration.zero,
        studyType: StudyType.learn,
      );
}
