import 'package:kentei_quiz/resource/lang/initial_resource.dart';
import 'package:kentei_quiz/resource/quiz/quiz_resource.dart';

import '../../controller/quiz_item/quiz_item_state.dart';

///問題ジャンル
List<QuizItemState> quizStudyItems = [
  QuizItemState(
    id: 1,
    group: I18n().group1,
    title: "問題A-1",
    isCompleted: false,
    quizList: quiz1,
    score: 0,
    timeStamp: null,
  ),
  QuizItemState(
    id: 2,
    group: I18n().group1,
    title: "問題A-2",
    isCompleted: false,
    quizList: quiz2,
    score: 0,
    timeStamp: null,
  ),
  QuizItemState(
    id: 3,
    group: I18n().group2,
    title: "問題B-1",
    isCompleted: false,
    quizList: quiz1,
    score: 0,
    timeStamp: null,
  ),
  QuizItemState(
    id: 4,
    group: I18n().group2,
    title: "問題B-2",
    isCompleted: false,
    quizList: quiz1,
    score: 0,
    timeStamp: null,
  ),
  QuizItemState(
    id: 5,
    group: I18n().group3,
    title: "問題C-1",
    isCompleted: false,
    quizList: quiz1,
    score: 0,
    timeStamp: null,
  ),
  QuizItemState(
    id: 6,
    group: I18n().group3,
    title: "問題C-2",
    isCompleted: false,
    quizList: quiz1,
    score: 0,
    timeStamp: null,
  ),
  QuizItemState(
    id: 7,
    group: I18n().group1,
    title: "問題A-3",
    isCompleted: false,
    quizList: quiz1,
    score: 0,
    timeStamp: null,
  ),
  QuizItemState(
    id: 8,
    group: I18n().group2,
    title: "問題B-3",
    isCompleted: false,
    quizList: quiz1,
    score: 0,
    timeStamp: null,
  ),
  QuizItemState(
    id: 9,
    group: I18n().group3,
    title: "問題C-3",
    isCompleted: false,
    quizList: quiz1,
    score: 0,
    timeStamp: null,
  ),
  QuizItemState(
    id: 10,
    group: I18n().group4,
    title: "問題D-1",
    isCompleted: false,
    quizList: quiz1,
    score: 0,
    timeStamp: null,
  ),
  QuizItemState(
    id: 11,
    group: I18n().group4,
    title: "問題D-2",
    isCompleted: false,
    quizList: quiz1,
    score: 0,
    timeStamp: null,
  ),
];
