// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCbaTc-9KzlCTeCTvlHrLwfhPt_yWKO01k',
    appId: '1:219522966725:web:5ccf8036444027524f3cac',
    messagingSenderId: '219522966725',
    projectId: 'kentei-quiz-18ce5',
    authDomain: 'kentei-quiz-18ce5.firebaseapp.com',
    storageBucket: 'kentei-quiz-18ce5.appspot.com',
    measurementId: 'G-8HZVMKD190',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCccT2iHPlLppePI3nL3kws7mFFpADs5gQ',
    appId: '1:219522966725:android:e424d75dec0443524f3cac',
    messagingSenderId: '219522966725',
    projectId: 'kentei-quiz-18ce5',
    storageBucket: 'kentei-quiz-18ce5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAF0MQH_iNfuvR7z3jczZyg3IV7dzcLZ3c',
    appId: '1:219522966725:ios:ac91c8ca6851c88b4f3cac',
    messagingSenderId: '219522966725',
    projectId: 'kentei-quiz-18ce5',
    storageBucket: 'kentei-quiz-18ce5.appspot.com',
    iosClientId: '219522966725-ahq8u9te7aacjo31ab73qq0krv07781t.apps.googleusercontent.com',
    iosBundleId: 'com.example.kenteiQuiz',
  );
}
